use crate::dtype::DType;
use crate::graph::{NodeId, TensorId};

/// Metadata about a tensor flowing through the graph.
///
/// This is compile-time metadata only  -  no actual data is stored.
#[derive(Debug, Clone)]
pub struct TensorMeta {
    pub(crate) id: TensorId,
    pub(crate) shape: Vec<usize>,
    pub(crate) dtype: DType,
    pub(crate) producer: Option<NodeId>,
    pub(crate) consumers: Vec<NodeId>,
    pub(crate) name: String,
}

impl TensorMeta {
    /// The unique identifier of this tensor.
    pub fn id(&self) -> TensorId {
        self.id
    }

    /// The shape (dimensions) of this tensor.
    pub fn shape(&self) -> &[usize] {
        &self.shape
    }

    /// The data type of this tensor's elements.
    pub fn dtype(&self) -> DType {
        self.dtype
    }

    /// Total number of elements in the tensor.
    pub fn elements(&self) -> u64 {
        self.shape.iter().fold(1u64, |acc, &d| acc.saturating_mul(d as u64))
    }

    /// Size of this tensor in bytes.
    pub fn byte_size(&self) -> u64 {
        self.dtype.byte_size_for_elements(self.elements())
    }

    /// The node that created this tensor (None if it's a graph input).
    pub fn producer(&self) -> Option<NodeId> {
        self.producer
    }

    /// The nodes that consume this tensor as input.
    pub fn consumers(&self) -> &[NodeId] {
        &self.consumers
    }

    /// Human-readable name (often autogenerated).
    pub fn name(&self) -> &str {
        &self.name
    }
}
